### PR TITLE
Feature/ci cd grafana prometheus

### PR DESCRIPTION
**Pull request by Kether180**
I'm currently working on fixing the CI/CD pipelines for Grafana and Prometheus, but so far I haven't been successful. 

I've added some data to the remote_files folder (docker-compose.yml) and to the continuous.deployment.yml, but still no luck. The only endpoint that seems to be working is /metrics and the grafana/prometheus part on local server, but not on https://157.230.79.99:9090 or https://157.230.79.99:3000.

If you have any tips or can provide some help, I would greatly appreciate it!

By the way, I've created a new Readme.me file that includes a short description of the project. Feel free to edit or add more information as you see fit.

### CODE REVIEW

**Comment by Kether180** [comment]
https://github.com/Group-O-Minitwit/minitwit-group-o/actions/runs/4569379971

Invalid workflow file: .github/workflows/continous-deployment.yml#L22You have an error in your yaml syntax on line 22

**Comment by Kether180** [comment]
Screenshot from 2023-03-27 09-28-43

**Comment by Kether180** [comment]
Screenshot from 2023-03-31 01-01-47

**Comment by Kether180** [comment]
Screenshot from 2023-03-31 01-01-58

**Comment by MikkelNilsson** [comment]
This works now! there was some errors with some paths that didn't match up, and the order in the deplotment file.

**Comment by MikkelNilsson** [comment]
Grafana is now running on http://157.230.79.99:3000 and prometheus on http://157.230.79.99:9090

**Comment by ChristofferTofteng** [comment]
Cant remember which of the links they wanted but we have to make a PR to the course branch with logging/monitoring link

**Review by Kether180 — COMMENTED** [review]
great , thanks .

**Pull request merged**
